// Generated by dts-bundle-generator v5.9.0

export declare abstract class M3u8 {
	readonly content: string;
	readonly lines: IM3u8Line[];
	/**
	 * @param {string} content the m3u8-formatted string
	 * @param {IM3u8Line[]} lines the parsed lines of the m3u8-formatted string
	 * @memberof M3u8
	 */
	constructor(content: string, lines: IM3u8Line[]);
	/**
	 * Returns the value of the first line of the specified tag.
	 *
	 * @param {M3u8Tag} tag the tag to match
	 * @return {*}  {IM3u8Line}
	 * @memberof M3u8
	 */
	findLineByTag(tag: M3u8Tag): IM3u8Line;
	/**
	 * Returns the value of the first line of the specified tag and line type.
	 *
	 * @param {M3u8LineType} type
	 * @param {M3u8Tag} tag
	 * @return {*}  {IM3u8Line}
	 * @memberof M3u8
	 */
	findLineTypeByTag(type: M3u8LineType, tag: M3u8Tag): IM3u8Line;
}
export declare class M3u8Slice implements IM3u8Producer {
	readonly meta: IM3u8Line[];
	readonly segments: IM3u8MediaSegment[];
	readonly offsetMillis: number;
	readonly mediaExhausted: boolean;
	private readonly terminate;
	/**
	 * @param {IM3u8Line[]} meta the metadata to include in the slice
	 * @param {IM3u8MediaSegment[]} segments the media segments to include in the slice
	 * @param {number} offsetMillis the offset in milliseconds from the beginning of the stream
	 * @param {boolean} mediaExhausted whether the media has been exhausted
	 * @param {boolean} terminate whether to terminate the slice with an EXT-X-ENDLIST tag
	 * @memberof M3u8Slice
	 */
	constructor(meta: IM3u8Line[], segments: IM3u8MediaSegment[], offsetMillis: number, mediaExhausted: boolean, terminate: boolean);
	/**
	 * Gets the total seconds offset from the beginning of the stream
	 * that this slice represents
	 *
	 * @readonly
	 * @type {number}
	 * @memberof M3u8Slice
	 */
	get offsetSeconds(): number;
	/**
	 * Immutably creates a new slice with the specified metadata inserted
	 * after the first tag that matches the predicate, or at the end of
	 * the metadata if no predicate is provided
	 *
	 * @param {M3u8Tag} tag the tag to insert
	 * @param {string} value the value to insert
	 * @param {Predicate} [after] if supplied, the new meta content will be inserted after the first tag that matches the predicate
	 * @return {*}  {M3u8Slice}
	 * @throws {Error} if the specified tag already exists in the slice
	 * @throws {Error} if the predicate, when used, does not match any tags
	 * @memberof M3u8Slice
	 */
	insertMeta(tag: M3u8Tag, value: string, after?: Predicate): M3u8Slice;
	/**
	 * Immutably creates a new slice with modified meta content
	 *
	 * @param {M3u8Tag} tag the tag to modify
	 * @param {MetaModifier} modifier the modifier function to apply
	 * @return {*}  {M3u8Slice}
	 * @throws {Error} if the tag is not found
	 * @memberof M3u8Slice
	 */
	modifyMeta(tag: M3u8Tag, modifier: MetaModifier): M3u8Slice;
	/**
	 * Immutably creates a new slice with the specified tag removed
	 *
	 * @param {M3u8Tag} tag the tag to remove
	 * @return {*}  {M3u8Slice}
	 * @throws {Error} if the tag is not found
	 * @memberof M3u8Slice
	 */
	omitMeta(tag: M3u8Tag): M3u8Slice;
	/**
	 * Immutably creates a new slice with modified segment content
	 *
	 * @param {SegmentModifier} modifier the modifier function to apply to each segment
	 * @return {*}  {M3u8Slice}
	 * @memberof M3u8Slice
	 */
	modifyEachSegment(modifier: SegmentModifier): M3u8Slice;
	/**
	 * Immutably creates a new slice with modified segment metadata. The
	 * modifier function will be applied to each segment that contains
	 * the specified meta tag
	 *
	 * @param {M3u8Tag} tag the tag to modify in each segment
	 * @param {SegmentMetaModifier} modifier the modifier function to apply to each segment that contains the tag
	 * @return {*}  {M3u8Slice}
	 * @throws {Error} if the tag is not found at least once
	 * @memberof M3u8Slice
	 */
	modifySegmentMeta(tag: M3u8Tag, modifier: SegmentMetaModifier): M3u8Slice;
	/**
	 * Immutably creates a new slice with the specified tag removed from
	 * each segment's metadata
	 *
	 * @param {M3u8Tag} tag the tag to remove from each segment's metadata
	 * @return {*}  {M3u8Slice}
	 * @throws {Error} if the tag is not found at least once
	 * @memberof M3u8Slice
	 */
	omitSegmentMeta(tag: M3u8Tag): M3u8Slice;
	/**
	 * Appends another slice to this slice, adding an EXT-X-DISCONTINUITY
	 * tag to the first segment of the appended slice. This mutates the
	 * current instance.
	 *
	 * @param {M3u8Slice} nextSlice the slice to append
	 * @memberof M3u8Slice
	 */
	appendDiscontinuity(nextSlice: M3u8Slice): void;
	/**
	 * @memberof M3u8Slice
	 * @inheritdoc
	 */
	marshal(): string;
	/**
	 * Create a deep clone of this slice
	 *
	 * @return {*}  {M3u8Slice}
	 * @memberof M3u8Slice
	 */
	clone(): M3u8Slice;
}
export declare class M3u8Slicer {
	private readonly m3u8;
	private readonly resolver;
	private readonly targetDurationMillis;
	/**
	 * @param {MediaM3u8} m3u8 the M3u8 instance to slice
	 * @param {TargetResolver} resolver the url/path target resolver instance
	 * @param {number} [speedRatio=1] the speed ratio to apply to segment durations (defaults to 1 = no change)
	 * @memberof M3u8Slicer
	 */
	constructor(m3u8: MediaM3u8, resolver: TargetResolver, speedRatio?: number);
	/**
	 * Get the segment count for the given m3u8 subject
	 *
	 * @readonly
	 * @type {number}
	 * @memberof LiveM3u8SliceGenerator
	 */
	get length(): number;
	/**
	 * Composes one or more M3u8 slices into the first
	 *
	 * @static
	 * @param {...M3u8Slice[]} slices the slices to compose
	 * @return {*}  {M3u8Slice}
	 * @memberof M3u8Slicer
	 */
	static compose(...slices: M3u8Slice[]): M3u8Slice;
	/**
	 * Slice the m3u8 subject into a new manifest for a live stream
	 *
	 * @param {number} sequence the value for the EXT-X-MEDIA-SEQUENCE tag
	 * @param {number} start the index of the first segment to include in the slice
	 * @param {number} count the number of segments to include in the slice
	 * @param {boolean} [isDvr=false] whether the slice is should include the "EVENT" value for the EXT-X-PLAYLIST-TYPE tag
	 * @return {*}  {M3u8Slice}
	 * @memberof M3u8Slicer
	 */
	toLiveSlice(sequence: number, start: number, count: number, isDvr?: boolean): M3u8Slice;
	/**
	 * Slice the m3u8 subject into a new manifest for a video-on-demand
	 *
	 * @param {number} start the index of the first segment to include in the slice
	 * @param {number} count the number of segments to include in the slice
	 * @return {*}  {M3u8Slice}
	 * @memberof M3u8Slicer
	 */
	toVodSlice(start: number, count: number): M3u8Slice;
	/**
	 * Slice the m3u8 subject into a new manifest for a live stream transition
	 *
	 * @param {number} sequence the value for the EXT-X-MEDIA-SEQUENCE tag
	 * @param {number} segmentIndex the index of the segment from which to start the transition
	 * @param {M3u8Slicer} next the slicer instance to which the transition will be applied
	 * @return {*}  {M3u8Slice}
	 * @memberof M3u8Slicer
	 */
	toLiveTransitionSlice(sequence: number, segmentIndex: number, next: M3u8Slicer): M3u8Slice;
	/**
	 * Marshal an array of segments, injecting values from the target url/path resolver
	 *
	 * @private
	 * @param {IM3u8MediaSegment[]} segments
	 * @return {*}  {IM3u8MediaSegment[]}
	 * @memberof M3u8Slicer
	 */
	private marshalSegments;
}
export declare class MasterM3u8 extends M3u8 {
	/**
	 * @param {string} content the m3u8-formatted string
	 * @throws {Error} if the content is not a valid master variant manifest
	 * @memberof MasterM3u8
	 */
	constructor(content: string);
	/**
	 * The media variants in the manifest
	 *
	 * @return {*}  {string[]}
	 * @memberof MasterM3u8
	 */
	get variants(): string[];
}
export declare class MediaM3u8 extends M3u8 {
	readonly lines: IM3u8Line[];
	readonly segments: IM3u8MediaSegment[];
	readonly meta: IM3u8Line[];
	/**
	 * @param {string} content the m3u8-formatted string
	 * @throws {Error} if the content is not a valid media segment manifest
	 * @memberof MediaM3u8
	 */
	constructor(content: string);
	/**
	 * Get the total segments count
	 *
	 * @return {*}  {number}
	 * @memberof MediaM3u8
	 */
	segmentCount(): number;
	/**
	 * Outputs the contents to an m3u8 slice
	 *
	 * @param {TargetResolver} resolver the url/path target resolver instance
	 * @return {*}  {M3u8Slice}
	 * @memberof MediaM3u8
	 */
	asSlice(resolver: TargetResolver): M3u8Slice;
}
export declare class TargetResolver {
	readonly resolveEncryptionKeyUrl: Resolver;
	readonly resolveSourcePathUrl: Resolver;
	/**
	 * @param {Resolver} resolveEncryptionKeyUrl operator that pipes the encryption key line to a custom URL
	 * @param {Resolver} resolveSourcePathUrl operator that pipes segment source values to a custom URL
	 * @memberof TargetResolver
	 */
	constructor(resolveEncryptionKeyUrl: Resolver, resolveSourcePathUrl: Resolver);
	/**
	 * The default resolver that does not modify the original values
	 *
	 * @static
	 * @return {*}  {TargetResolver}
	 * @memberof TargetResolver
	 */
	static default(): TargetResolver;
}
/**
 * Enumeration that discriminates the type/purpose/scope of a line in an M3U8 file.
 *
 * @export
 * @enum {string}
 */
export declare enum M3u8LineType {
	/**
	 * The first line of any m3u8 file (EXT_M3U)
	 */
	HEADER = "HEADER",
	/**
	 * Lines that contain metadata for the entire m3u8
	 */
	META = "META",
	/**
	 * Lines that contain metadata for a single segment
	 */
	SEGMENT_META = "SEGMENT_META",
	/**
	 * Lines that contain the source path for a single segment
	 */
	SEGMENT_SRC = "SEGMENT_SRC",
	/**
	 * Lines that contain metadata for m3u8 variants
	 */
	VARIANT_META = "VARIANT_META",
	/**
	 * Lines that contain the source path for m3u8 variants
	 */
	VARIANT_SRC = "VARIANT_SRC",
	/**
	 * Final line of any m3u8 file (EXT_X_ENDLIST)
	 */
	FOOTER = "FOOTER",
	/**
	 * Any line containing a tag that is not used by this library
	 */
	UNUSED = "UNUSED",
	/**
	 * Any line containing a META tag that is specific to the Montage M3U8 spec
	 */
	MONTAGE_META = "MONTAGE_META"
}
/**
 * Enumeration that contains the possible tags that can be found in an M3U8 file.
 *
 * Each enum key represents the actual text of the tag, minus the preceding `#` symbol,
 * and substitutes hyphens with underscores.
 *
 * @export
 * @enum {string}
 */
export declare enum M3u8Tag {
	EXT_M3U = "#EXTM3U",
	EXT_X_VERSION = "#EXT-X-VERSION",
	EXT_X_TARGETDURATION = "#EXT-X-TARGETDURATION",
	EXT_X_MEDIA_SEQUENCE = "#EXT-X-MEDIA-SEQUENCE",
	EXT_X_DISCONTINUITY_SEQUENCE = "#EXT-X-DISCONTINUITY-SEQUENCE",
	EXT_X_PROGRAM_DATE_TIME = "#EXT-X-PROGRAM-DATE-TIME",
	EXT_X_ENDLIST = "#EXT-X-ENDLIST",
	EXT_X_PLAYLIST_TYPE = "#EXT-X-PLAYLIST-TYPE",
	EXT_X_I_FRAMES_ONLY = "#EXT-X-I-FRAMES-ONLY",
	EXT_X_INDEPENDENT_SEGMENTS = "#EXT-X-INDEPENDENT-SEGMENTS",
	EXT_X_START = "#EXT-X-START",
	EXT_X_MAP = "#EXT-X-MAP",
	EXT_X_I_FRAME_STREAM_INF = "#EXT-X-I-FRAME-STREAM-INF",
	EXT_X_STREAM_INF = "#EXT-X-STREAM-INF",
	EXT_X_SESSION_DATA = "#EXT-X-SESSION-DATA",
	EXT_X_SESSION_KEY = "#EXT-X-SESSION-KEY",
	EXT_X_KEY = "#EXT-X-KEY",
	EXT_X_BYTERANGE = "#EXT-X-BYTERANGE",
	EXT_X_DISCONTINUITY = "#EXT-X-DISCONTINUITY",
	EXT_X_PART = "#EXT-X-PART",
	EXT_X_PART_INF = "#EXT-X-PART-INF",
	EXT_X_PRELOAD_HINT = "#EXT-X-PRELOAD-HINT",
	EXT_X_SERVER_CONTROL = "#EXT-X-SERVER-CONTROL",
	EXT_X_SKIP = "#EXT-X-SKIP",
	EXT_X_SKIP_INF = "#EXT-X-SKIP-INF",
	EXT_X_MEDIA = "#EXT-X-MEDIA",
	EXTINF = "#EXTINF",
	EXT_X_MONTAGE_SOURCE_SEQUENCE = "#EXT-X-MONTAGE-SOURCE-SEQUENCE"
}
export declare type MetaModifier = (original: string) => string;
export declare type Predicate = (line: IM3u8Line) => boolean;
export declare type Resolver = (originalValue: string) => string;
export declare type SegmentMetaModifier = (original: IM3u8Line, segmentIndex: number, metaIndex: number) => string;
export declare type SegmentModifier = (original: IM3u8MediaSegment, index: number) => IM3u8MediaSegment;
/**
 * Represents a line in an M3U8 file.
 *
 * @export
 * @interface IM3u8Line
 */
export interface IM3u8Line {
	/**
	 * The type of line this is.
	 *
	 * @type {M3u8LineType}
	 * @memberof IM3u8Line
	 */
	type: M3u8LineType;
	/**
	 * The entirety of the line.
	 *
	 * @type {string}
	 * @memberof IM3u8Line
	 */
	content: string;
	/**
	 * The tag of the line, if present
	 *
	 * @type {M3u8Tag}
	 * @memberof IM3u8Line
	 */
	tag?: M3u8Tag;
	/**
	 * The value of the line, if present. If no tag is
	 * present, this is identical to the content.
	 *
	 * @type {string}
	 * @memberof IM3u8Line
	 */
	value: string;
}
/**
 * Represents a content segment of an M3U8 file.
 *
 * @export
 * @interface IM3u8MediaSegment
 */
export interface IM3u8MediaSegment {
	/**
	 * An array of metadata lines germane to this segment.
	 *
	 * @type {IM3u8Line[]}
	 * @memberof IM3u8MediaSegment
	 */
	meta: IM3u8Line[];
	/**
	 * The source URL of the segment.
	 *
	 * @type {string}
	 * @memberof IM3u8MediaSegment
	 */
	source: string;
	/**
	 * The duration of the segment, in seconds, as a floating point number.
	 *
	 * @type {number}
	 * @memberof IM3u8MediaSegment
	 */
	duration: number;
}
/**
 * Represents a producer of M3U8 files that can marshal
 * its contents into a string.
 *
 * @export
 * @interface IM3u8Producer
 */
export interface IM3u8Producer {
	/**
	 * Marshal the contents to an m3u8-formatted string
	 *
	 * @return {*}  {string}
	 * @memberof IM3u8Producer
	 */
	marshal(): string;
}

export as namespace MontageM3u8Lib;

export {};
