
/**
 * Enumeration that contains the possible tags that can be found in an M3U8 file.
 *
 * Each enum key represents the actual text of the tag, minus the preceding `#` symbol,
 * and substitutes hyphens with underscores.
 *
 * @export
 * @enum {string}
 */
export enum M3u8Tag {
  EXT_M3U = '#EXTM3U',
  EXT_X_VERSION = '#EXT-X-VERSION',
  EXT_X_TARGETDURATION = '#EXT-X-TARGETDURATION',
  EXT_X_MEDIA_SEQUENCE = '#EXT-X-MEDIA-SEQUENCE',
  EXT_X_DISCONTINUITY_SEQUENCE = '#EXT-X-DISCONTINUITY-SEQUENCE',
  EXT_X_PROGRAM_DATE_TIME = '#EXT-X-PROGRAM-DATE-TIME',
  EXT_X_ENDLIST = '#EXT-X-ENDLIST',
  EXT_X_PLAYLIST_TYPE = '#EXT-X-PLAYLIST-TYPE',
  EXT_X_I_FRAMES_ONLY = '#EXT-X-I-FRAMES-ONLY',
  EXT_X_INDEPENDENT_SEGMENTS = '#EXT-X-INDEPENDENT-SEGMENTS',
  EXT_X_START = '#EXT-X-START',
  EXT_X_MAP = '#EXT-X-MAP',
  EXT_X_I_FRAME_STREAM_INF = '#EXT-X-I-FRAME-STREAM-INF',
  EXT_X_STREAM_INF = '#EXT-X-STREAM-INF',
  EXT_X_SESSION_DATA = '#EXT-X-SESSION-DATA',
  EXT_X_SESSION_KEY = '#EXT-X-SESSION-KEY',
  EXT_X_KEY = '#EXT-X-KEY',
  EXT_X_BYTERANGE = '#EXT-X-BYTERANGE',
  EXT_X_DISCONTINUITY = '#EXT-X-DISCONTINUITY',
  EXT_X_PART = '#EXT-X-PART',
  EXT_X_PART_INF = '#EXT-X-PART-INF',
  EXT_X_PRELOAD_HINT = '#EXT-X-PRELOAD-HINT',
  EXT_X_SERVER_CONTROL = '#EXT-X-SERVER-CONTROL',
  EXT_X_SKIP = '#EXT-X-SKIP',
  EXT_X_SKIP_INF = '#EXT-X-SKIP-INF',
  EXT_X_MEDIA = '#EXT-X-MEDIA',
  EXTINF = '#EXTINF',
}
